function wdialog
    d = dialog('Position',[300 300 250 150],'Name','My Dialog');

    txt = uicontrol('Parent',d,...
               'Style','text',...
           'FontUnits',20,...
               'Position',[20 80 210 40],...
               'String','Pressing OK will plot welch power density, this could take a long time\');

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','OK',...
               'Callback','delete(gcf)');
end
